### ISSUE TITLE
gem包依赖导致rails5无法使用呢

### ISSUE THREAD

**Issue by zouchao** [souche/ons_on_rails#1]
ruby版本：ruby 2.3.1p112

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/sean/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rice-2.1.0
/Users/sean/.rbenv/versions/2.3.1/bin/ruby -r ./siteconf20161014-27748-14yf98m.rb extconf.rb
Unfortunately Rice does not build against a staticly linked Ruby.
You'll need to rebuild Ruby with --enable-shared to use this library.

If you're on rvm:   rvm reinstall [version] -- --enable-shared
If you're on rbenv: CONFIGURE_OPTS="--enable-shared" rbenv install [version]

If you are using Heroku, they use a own custom configured, staticly linked Ruby
for their stack and it unfortunately does not work with Rice. You will need to use
a custom Ruby build pack that builds and uses a non-static version of Ruby.

extconf failed, exit code 1
```

**Comment by ghost** [comment]
这个项目依赖 [ons](https://github.com/souche/aliyun-ons-ruby-sdk)，而 ons 底层实现是基于阿里云 ONS C++ SDK，由于阿里云官方提供的 SDK 没有对应的 Mac OS X 的静态/动态库，目前 ons 这个软件包只能安装在 Linux 系统。

在 ons_on_rails 设计时，考虑到需要在 Mac OS X 做开发的情形，虽然通过适配器等方式没有直接引用 ons，但是在实际测试或是正式部署时，还是需要真实的 Linux 系统的。对于消息队列相关功能的开发，可以考虑使用 vagrant 来管理虚拟机，并在之上开发。

另外，如果你只是需要在 Mac OS X 上做无关消息队列的开发，其实并不需要实际启动消费者或是通过生产者发送消息。那么
- 安装依赖时，执行 `bundle --without linux` 即可
- 消费者，无；限制是无法使用 `bundle exec ruby daemons/xxxx_control.rb start` 来启动消费者
- 生成者，将 backend 设置为 :test 模式；限制是不会通过 :tcp 产生实际消息

**Comment by zouchao** [comment]
@0x005a 谢谢，明白了
